<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Outlet;
use App\Models\Product;
use App\Models\Review;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Create Default Admin User
        User::updateOrCreate(
            ['email' => 'admin@dadarberedar.com'],
            [
                'name' => 'Admin Dadar Beredar',
                'password' => bcrypt('password123'),
            ]
        );

        // 2. Seed Outlets
        $outlets = [
            [
                'name' => 'Dadar Beredar Sidoarjo (Pusat Sidoarjo)',
                'slug' => 'dadar-beredar-sidoarjo',
                'city' => 'Sidoarjo',
                'province' => 'Jawa Timur',
                'address' => 'Jl. Pahlawan No. 45, Sidokumpul, Kec. Sidoarjo, Kabupaten Sidoarjo, Jawa Timur 61213 (Dekat Alun-alun & GOR Sidoarjo)',
                'latitude' => -7.447812,
                'longitude' => 112.718321,
                'phone' => '+62 812-3456-7890',
                'whatsapp' => '6281234567890',
                'opening_hours' => '10:00 - 22:30 WIB',
                'rating' => 4.9,
                'review_count' => 2840,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Sidoarjo',
                'gmaps_place_id' => 'ChIJsidoarjo_dadar_beredar_01',
                'gofood_url' => 'https://gofood.co.id/sidoarjo/restaurant/dadar-beredar-b91c890f-4886-42d8-9a63-71b69324e930',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurant/dadar-beredar-sidokumpul-delivery-menu/6-C3KTLNTKT2TGVA',
                'shopeefood_url' => 'https://shopee.co.id/universal-link/now-food/shop/21888492',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Waru Tropodo',
                'slug' => 'dadar-beredar-waru-tropodo',
                'city' => 'Sidoarjo',
                'province' => 'Jawa Timur',
                'address' => 'Jl. Raya Tropodo No. 88, Tropodo Wetan, Kec. Waru, Kabupaten Sidoarjo, Jawa Timur 61256 (Akses Strategis Juanda & Bundaran Waru)',
                'latitude' => -7.365420,
                'longitude' => 112.764850,
                'phone' => '+62 812-8899-7766',
                'whatsapp' => '6281288997766',
                'opening_hours' => '10:00 - 23:00 WIB',
                'rating' => 4.9,
                'review_count' => 1680,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Waru+Tropodo+Sidoarjo',
                'gmaps_place_id' => 'ChIJwaru_tropodo_dadar_05',
                'gofood_url' => 'https://gofood.co.id/sidoarjo/restaurant/dadar-beredar-waru-tropodo',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurant/dadar-beredar-waru-tropodo-delivery-menu/6-C4ABLTWKT3X7VA',
                'shopeefood_url' => 'https://shopee.co.id/universal-link/now-food/shop/21990412',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Surabaya MERR',
                'slug' => 'dadar-beredar-surabaya-merr',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'address' => 'Jl. Dr. Ir. H. Soekarno (MERR) No. 128, Rungkut, Surabaya, Jawa Timur 60298',
                'latitude' => -7.291240,
                'longitude' => 112.782410,
                'phone' => '+62 812-7890-1234',
                'whatsapp' => '6281278901234',
                'opening_hours' => '10:00 - 23:00 WIB',
                'rating' => 4.8,
                'review_count' => 3150,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Surabaya+MERR',
                'gmaps_place_id' => 'ChIJsurabaya_merr_dadar_02',
                'gofood_url' => 'https://gofood.co.id/surabaya/restaurant/dadar-beredar-surabaya-merr',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurant/dadar-beredar-merr-delivery-menu/6-C2KTMNTKT1AGVA',
                'shopeefood_url' => 'https://shopee.co.id/universal-link/now-food/shop/21888495',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Surabaya Barat (G-Walk)',
                'slug' => 'dadar-beredar-surabaya-barat',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'address' => 'Ruko Taman Gapura G-Walk CitraLand Blok K-15, Sambikerep, Surabaya Barat',
                'latitude' => -7.288500,
                'longitude' => 112.645200,
                'phone' => '+62 813-9876-5432',
                'whatsapp' => '6281398765432',
                'opening_hours' => '11:00 - 23:00 WIB',
                'rating' => 4.8,
                'review_count' => 1980,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Citraland+Surabaya',
                'gmaps_place_id' => 'ChIJgwalk_dadar_surabaya_03',
                'gofood_url' => 'https://gofood.co.id/surabaya/restaurant/dadar-beredar-gwalk',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurant/dadar-beredar-gwalk-delivery-menu/6-C2KTGNTKT2BGVA',
                'shopeefood_url' => 'https://shopee.co.id/universal-link/now-food/shop/21888496',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Tebet Jakarta Selatan',
                'slug' => 'dadar-beredar-tebet-jakarta',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'address' => 'Jl. Tebet Timur Dalam Raya No. 34, Tebet, Jakarta Selatan 12820',
                'latitude' => -6.228400,
                'longitude' => 106.853200,
                'phone' => '+62 811-2233-4455',
                'whatsapp' => '6281122334455',
                'opening_hours' => '10:00 - 23:00 WIB',
                'rating' => 4.9,
                'review_count' => 5420,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Tebet+Jakarta',
                'gmaps_place_id' => 'ChIJtebet_dadar_jakarta_04',
                'gofood_url' => 'https://gofood.co.id/jakarta/restaurant/dadar-beredar-tebet',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurant/dadar-beredar-tebet-delivery-menu/6-C1KTANTKT5CGVA',
                'shopeefood_url' => 'https://shopee.co.id/universal-link/now-food/shop/21888497',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Medan Marelan (Tanah Kelahiran Babe)',
                'slug' => 'dadar-beredar-medan-marelan',
                'city' => 'Medan',
                'province' => 'Sumatera Utara',
                'address' => 'Jl. Marelan Raya No. 88, Tanah Enam Ratus, Medan Marelan, Kota Medan 20245',
                'latitude' => 3.662100,
                'longitude' => 98.673400,
                'phone' => '+62 812-4455-6677',
                'whatsapp' => '6281244556677',
                'opening_hours' => '10:00 - 22:30 WIB',
                'rating' => 4.9,
                'review_count' => 4890,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Medan+Marelan',
                'gmaps_place_id' => 'ChIJmedan_dadar_babe_05',
                'gofood_url' => 'https://gofood.co.id/medan/restaurant/dadar-beredar-medan-marelan',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurant/dadar-beredar-marelan-delivery-menu/6-C5KTXNTKT7DGVA',
                'shopeefood_url' => 'https://shopee.co.id/universal-link/now-food/shop/21888498',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Bandung Dipatiukur',
                'slug' => 'dadar-beredar-bandung-dipatiukur',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'address' => 'Jl. Dipatiukur No. 72, Lebakgede, Coblong, Kota Bandung, Jawa Barat 40132',
                'latitude' => -6.892300,
                'longitude' => 107.618500,
                'phone' => '+62 821-3344-5566',
                'whatsapp' => '6282133445566',
                'opening_hours' => '10:00 - 22:00 WIB',
                'rating' => 4.8,
                'review_count' => 2640,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Dipatiukur+Bandung',
                'gmaps_place_id' => 'ChIJbandung_dadar_du_06',
                'gofood_url' => 'https://gofood.co.id/bandung/restaurant/dadar-beredar-dipatiukur',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurant/dadar-beredar-dipatiukur-delivery-menu/6-C3KTBNTKT8EGVA',
                'shopeefood_url' => 'https://shopee.co.id/universal-link/now-food/shop/21888499',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Yogyakarta Seturan',
                'slug' => 'dadar-beredar-yogyakarta-seturan',
                'city' => 'Yogyakarta',
                'province' => 'DI Yogyakarta',
                'address' => 'Jl. Seturan Raya No. 16, Caturtunggal, Depok, Sleman, Yogyakarta 55281',
                'latitude' => -7.765400,
                'longitude' => 110.408200,
                'phone' => '+62 856-1122-3344',
                'whatsapp' => '6285611223344',
                'opening_hours' => '10:00 - 23:00 WIB',
                'rating' => 4.9,
                'review_count' => 3810,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Seturan+Jogja',
                'gmaps_place_id' => 'ChIJjogja_dadar_seturan_07',
                'gofood_url' => 'https://gofood.co.id/yogyakarta/restaurant/dadar-beredar-seturan',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurant/dadar-beredar-seturan-delivery-menu/6-C3KTJNTKT9FGVA',
                'shopeefood_url' => 'https://shopee.co.id/universal-link/now-food/shop/21888500',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Malang Soekarno Hatta',
                'slug' => 'dadar-beredar-malang-suhat',
                'city' => 'Malang',
                'province' => 'Jawa Timur',
                'address' => 'Jl. Soekarno Hatta No. 42B, Jatimulyo, Lowokwaru, Kota Malang 65141',
                'latitude' => -7.943200,
                'longitude' => 112.617400,
                'phone' => '+62 819-2233-4455',
                'whatsapp' => '6281922334455',
                'opening_hours' => '10:00 - 22:00 WIB',
                'rating' => 4.8,
                'review_count' => 2130,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Suhat+Malang',
                'gmaps_place_id' => 'ChIJmalang_suhat_dadar_08',
                'gofood_url' => 'https://gofood.co.id/malang/restaurant/dadar-beredar-suhat',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurant/dadar-beredar-suhat-delivery-menu/6-C3KTMNTKT0GGVA',
                'shopeefood_url' => 'https://shopee.co.id/universal-link/now-food/shop/21888501',
                'is_active' => true,
            ]
        ];

        foreach ($outlets as $outletData) {
            Outlet::updateOrCreate(['slug' => $outletData['slug']], $outletData);
        }

        $sidoarjoOutlet = Outlet::where('slug', 'dadar-beredar-sidoarjo')->first();

        // 3. Seed Categories
        $categories = [
            [
                'name' => 'Telur Ceplok Original',
                'slug' => 'telur-ceplok-original',
                'type' => 'food',
                'icon' => '🍳',
                'sort_order' => 1,
            ],
            [
                'name' => 'Telur Dadar Original',
                'slug' => 'telur-dadar-original',
                'type' => 'food',
                'icon' => '🥞',
                'sort_order' => 2,
            ],
            [
                'name' => 'Telur Ceplok Bakar',
                'slug' => 'telur-ceplok-bakar',
                'type' => 'food',
                'icon' => '🔥',
                'sort_order' => 3,
            ],
            [
                'name' => 'Telur Dadar Bakar',
                'slug' => 'telur-dadar-bakar',
                'type' => 'food',
                'icon' => '🍳🔥',
                'sort_order' => 4,
            ],
            [
                'name' => 'Dargor & Menu Baru',
                'slug' => 'dargor-menu-baru',
                'type' => 'food',
                'icon' => '🥘',
                'sort_order' => 5,
            ],
            [
                'name' => 'Paket Pengedar',
                'slug' => 'paket-pengedar',
                'type' => 'combo',
                'icon' => '🍱',
                'sort_order' => 6,
            ],
            [
                'name' => 'Kids Meals',
                'slug' => 'kids-meals',
                'type' => 'food',
                'icon' => '👶',
                'sort_order' => 7,
            ],
            [
                'name' => 'Minuman Segar',
                'slug' => 'minuman-segar',
                'type' => 'beverage',
                'icon' => '🥤',
                'sort_order' => 8,
            ],
            [
                'name' => 'Menu Tambahan (Add-on)',
                'slug' => 'menu-tambahan',
                'type' => 'side',
                'icon' => '🥣',
                'sort_order' => 9,
            ],
            [
                'name' => 'Upgrade & Tambahan',
                'slug' => 'upgrade-biaya-tambahan',
                'type' => 'side',
                'icon' => '➕',
                'sort_order' => 10,
            ],
        ];

        $catMap = [];
        foreach ($categories as $catData) {
            $category = Category::updateOrCreate(['slug' => $catData['slug']], $catData);
            $catMap[$catData['slug']] = $category->id;
        }

        // 4. Seed Products
        $products = [
            // 1. Telur Ceplok Original
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Lugu',
                'slug' => 'telur-ceplok-lugu',
                'description' => 'Telur ceplok goreng lezat khas Dadar Beredar dengan racikan bumbu lugu gurih nikmat.',
                'price' => 12273,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-ceplok-lugu.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Ayam Suwir',
                'slug' => 'telur-ceplok-ayam-suwir',
                'description' => 'Telur ceplok hangat disajikan dengan topping ayam suwir gurih berbumbu rempah meresap.',
                'price' => 24091,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-ayam-suwir.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Ceker',
                'slug' => 'telur-ceplok-ceker',
                'description' => 'Telur ceplok nikmat dipadukan dengan olahan ceker empuk bumbu gurih lezat.',
                'price' => 25000,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-ceker.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Kulit',
                'slug' => 'telur-ceplok-kulit',
                'description' => 'Telur ceplok disajikan bersama kulit ayam goreng renyah kriuk berselimut bumbu khas.',
                'price' => 25000,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-kulit.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Paru',
                'slug' => 'telur-ceplok-paru',
                'description' => 'Telur ceplok mantap disandingkan dengan paru sapi goreng gurih tanpa alot.',
                'price' => 26818,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-ceplok-paru.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Ayam Teriyaki',
                'slug' => 'telur-ceplok-ayam-teriyaki',
                'description' => 'Telur ceplok dipadukan dengan ayam saus teriyaki manis gurih lezat menggoda selera.',
                'price' => 26363,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-ayam-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Cumi Teriyaki',
                'slug' => 'telur-ceplok-cumi-teriyaki',
                'description' => 'Telur ceplok lezat dengan potongan cumi kenyal berbalut saus teriyaki manis gurih.',
                'price' => 28636,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-cumi-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Cumi',
                'slug' => 'telur-ceplok-cumi',
                'description' => 'Telur ceplok spesial dengan olahan cumi gurih pedas nikmat menggugah selera.',
                'price' => 28636,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-ceplok-cumi.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],

            // 2. Telur Dadar Original
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Lugu',
                'slug' => 'telur-dadar-lugu',
                'description' => 'Telur dadar kress keriting renyah khas Dadar Beredar dengan bumbu lugu gurih.',
                'price' => 12273,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-dadar-lugu.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Ayam Suwir',
                'slug' => 'telur-dadar-ayam-suwir',
                'description' => 'Telur dadar kress dengan taburan ayam suwir bumbu gurih lezat melimpah.',
                'price' => 23636,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-dadar-ayam-suwir.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Ceker',
                'slug' => 'telur-dadar-ceker',
                'description' => 'Telur dadar renyah disajikan dengan olahan ceker empuk bumbu rempah nikmat.',
                'price' => 24545,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-dadar-ceker.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Kulit',
                'slug' => 'telur-dadar-kulit',
                'description' => 'Telur dadar crispy gurih disandingkan dengan kulit ayam kriuk renyah maksimal.',
                'price' => 24545,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-dadar-kulit.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Paru',
                'slug' => 'telur-dadar-paru',
                'description' => 'Telur dadar crispy berpadu dengan paru goreng gurih empuk khas Dadar Beredar.',
                'price' => 26364,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-dadar-paru.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Ayam Teriyaki',
                'slug' => 'telur-dadar-ayam-teriyaki',
                'description' => 'Telur dadar gurih disiram topping ayam teriyaki manis legit beraroma khas.',
                'price' => 25455,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-dadar-ayam-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Cumi Teriyaki',
                'slug' => 'telur-dadar-cumi-teriyaki',
                'description' => 'Telur dadar renyah dipadukan dengan cumi teriyaki manis gurih istimewa.',
                'price' => 28182,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-dadar-cumi-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Cumi',
                'slug' => 'telur-dadar-cumi',
                'description' => 'Telur dadar crispy legendaris ditemani olahan cumi pedas gurih sedap.',
                'price' => 28182,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-dadar-cumi.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],

            // 3. Telur Ceplok Bakar
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Ayam Suwir',
                'slug' => 'telur-ceplok-bakar-ayam-suwir',
                'description' => 'Telur ceplok bakar bumbu smokey dipadukan dengan ayam suwir gurih lezat.',
                'price' => 25000,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-bakar-ayam-suwir.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Ceker',
                'slug' => 'telur-ceplok-bakar-ceker',
                'description' => 'Telur ceplok bakar aroma arang sedap ditemani ceker empuk bumbu bakar pedas manis.',
                'price' => 25909,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-bakar-ceker.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Kulit',
                'slug' => 'telur-ceplok-bakar-kulit',
                'description' => 'Telur ceplok bakar bumbu rempah bakar disajikan bersama kulit ayam krispy gurih.',
                'price' => 25909,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-bakar-kulit.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Paru',
                'slug' => 'telur-ceplok-bakar-paru',
                'description' => 'Telur ceplok bakar harum smokey dipadu paru goreng gurih empuk memanjakan lidah.',
                'price' => 27727,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-ceplok-bakar-paru.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Ayam Teriyaki',
                'slug' => 'telur-ceplok-bakar-ayam-teriyaki',
                'description' => 'Telur ceplok bakar dengan paduan ayam saus teriyaki manis gurih beraroma bakar.',
                'price' => 26818,
                'spiciness_level' => 1,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-bakar-ayam-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Cumi Teriyaki',
                'slug' => 'telur-ceplok-bakar-cumi-teriyaki',
                'description' => 'Telur ceplok bakar istimewa berpadu dengan cumi bumbu teriyaki manis legit.',
                'price' => 29545,
                'spiciness_level' => 1,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-bakar-cumi-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Cumi',
                'slug' => 'telur-ceplok-bakar-cumi',
                'description' => 'Telur ceplok bakar harum smokey dengan olahan cumi pedas gurih bumbu rempah bakar.',
                'price' => 29545,
                'spiciness_level' => 3,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-ceplok-bakar-cumi.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],

            // 4. Telur Dadar Bakar
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Ayam Suwir',
                'slug' => 'telur-dadar-bakar-ayam-suwir',
                'description' => 'Telur dadar tebal dibakar bumbu rempah manis gurih disandingkan dengan ayam suwir lezat.',
                'price' => 24545,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-dadar-bakar-ayam-suwir.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Ceker',
                'slug' => 'telur-dadar-bakar-ceker',
                'description' => 'Telur dadar bakar aroma rempah arang sedap dengan ceker pedas empuk meresap.',
                'price' => 25455,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-dadar-bakar-ceker.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Kulit',
                'slug' => 'telur-dadar-bakar-kulit',
                'description' => 'Telur dadar bakar gurih smokey ditemani kulit ayam goreng super renyah.',
                'price' => 25455,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-dadar-bakar-kulit.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Paru',
                'slug' => 'telur-dadar-bakar-paru',
                'description' => 'Menu andalan! Telur dadar tebal dibakar smokey berpadu paru sapi empuk gurih juara.',
                'price' => 27273,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-dadar-bakar-paru.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Ayam Teriyaki',
                'slug' => 'telur-dadar-bakar-ayam-teriyaki',
                'description' => 'Telur dadar bakar gurih disajikan dengan topping ayam bumbu teriyaki manis mantap.',
                'price' => 26818,
                'spiciness_level' => 1,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-dadar-bakar-ayam-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Cumi Teriyaki',
                'slug' => 'telur-dadar-bakar-cumi-teriyaki',
                'description' => 'Telur dadar bakar harum bumbu spesial dipadu cumi empuk berbalut saus teriyaki gurih.',
                'price' => 29091,
                'spiciness_level' => 1,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-dadar-bakar-cumi-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Cumi',
                'slug' => 'telur-dadar-bakar-cumi',
                'description' => 'Kombinasi terfavorit! Telur dadar bakar aroma smokey dengan olahan cumi pedas nikmat nendang.',
                'price' => 29091,
                'spiciness_level' => 3,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-dadar-bakar-cumi.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],

            // 5. Dargor & Menu Baru
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Ceker Crispy',
                'slug' => 'ceker-crispy',
                'description' => 'Ceker ayam pilihan digoreng super renyah kriuk dengan balutan tepung bumbu rempah gurih khas Dadar Beredar.',
                'price' => 9545,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/ceker-crispy.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Dargor Ayam Suwir',
                'slug' => 'dargor-ayam-suwir',
                'description' => 'Sajian Dargor spesial berpadu suwiran daging ayam gurih bumbu rempah meresap mantap.',
                'price' => 25000,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/dargor-ayam-suwir.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Dargor Kulit',
                'slug' => 'dargor-kulit',
                'description' => 'Dargor renyah disajikan dengan topping kulit ayam goreng krispy keemasan yang gurih maksimal.',
                'price' => 25909,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/dargor-kulit.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Dargor Ceker',
                'slug' => 'dargor-ceker',
                'description' => 'Dargor khas dipadukan dengan olahan ceker empuk berbumbu pedas manis sedap.',
                'price' => 25909,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/dargor-ceker.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Dargor Paru',
                'slug' => 'dargor-paru',
                'description' => 'Kombinasi juara Dargor dengan paru sapi goreng gurih renyah tanpa bau amis.',
                'price' => 27727,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/dargor-paru.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Dargor Cumi',
                'slug' => 'dargor-cumi',
                'description' => 'Sajian Dargor istimewa bertabur potongan cumi empuk gurih bumbu pedas nampol.',
                'price' => 29545,
                'spiciness_level' => 3,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/dargor-cumi.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Dargor Daging',
                'slug' => 'dargor-daging',
                'description' => 'Menu premium Dargor dengan potongan daging sapi empuk berbumbu rempah spesial kaya rasa.',
                'price' => 39545,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/dargor-daging.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],

            // 6. Kids Meals
            [
                'category_id' => $catMap['kids-meals'],
                'name' => 'Kids Meal: Ceplok Ayam Teriyaki',
                'slug' => 'kids-meal-ceplok-ayam-teriyaki',
                'description' => 'Porsi pas untuk si kecil: Nasi hangat, telur ceplok empuk, dan potongan ayam saus teriyaki manis gurih tanpa pedas.',
                'price' => 24545,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/kids-meal-ceplok-ayam-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['kids-meals'],
                'name' => 'Kids Meal: Dadar Ayam Teriyaki',
                'slug' => 'kids-meal-dadar-ayam-teriyaki',
                'description' => 'Porsi favorit anak: Nasi hangat, telur dadar kress gurih lembut, dan ayam bumbu teriyaki manis lezat.',
                'price' => 23182,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/kids-meal-dadar-ayam-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],

            // 6. Paket Pengedar (Bundling Promo Hemat)
            [
                'category_id' => $catMap['paket-pengedar'],
                'name' => 'Paketan Pengedar 1',
                'slug' => 'paketan-pengedar-1',
                'description' => 'Paket hemat Pengedar 1: 1 Dadar Ayam Suwir + 1 Dadar Jagung + 1 Es Sweet Greentea. Dari Rp 37.727 menjadi Rp 33.636.',
                'price' => 33636,
                'original_price' => 37727,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/paketan-pengedar-1.jpg',
                'type' => 'combo',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['paket-pengedar'],
                'name' => 'Pengedar 2',
                'slug' => 'pengedar-2',
                'description' => 'Paket kombo berdua: 2 Es Teh Small + 1 Dargor Paru + 1 Dadar Bakar Ayam Teriyaki. Dari Rp 75.909 menjadi Rp 61.818.',
                'price' => 61818,
                'original_price' => 75909,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/pengedar-2.jpg',
                'type' => 'combo',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['paket-pengedar'],
                'name' => 'Pengedar 3',
                'slug' => 'pengedar-3',
                'description' => 'Paket pesta rame-rame: 2 Dadar Cumi Teriyaki + 2 Dadar Ayam Suwir + 2 Dargor Paru + 1 Dadar Kulit + 3 Es Coklat + 4 Es Sweet Greentea. Dari Rp 272.271 menjadi Rp 248.182.',
                'price' => 248182,
                'original_price' => 272271,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/pengedar-3.jpg',
                'type' => 'combo',
                'stock' => 999,
                'is_available' => true,
            ],

            // 7. Minuman Segar
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Es Kopi Susu Botol',
                'slug' => 'es-kopi-susu-botol',
                'description' => 'Kopi susu gula aren creamy dalam botol praktis siap minum, perpaduan manis gurih pas teman makan telur dadar.',
                'price' => 10909,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/es-kopi-susu-botol.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Es Blackcurrant Squash',
                'slug' => 'es-blackcurrant-squash',
                'description' => 'Sensasi soda dingin dipadu sirup blackcurrant manis asam segar ampuh melepas dahaga.',
                'price' => 12727,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/es-blackcurrant-squash.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Es Jeruk Nipis',
                'slug' => 'es-jeruk-nipis',
                'description' => 'Jeruk nipis peras asli disajikan dingin dengan es batu kristal yang asam manis segar alami.',
                'price' => 9091,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/es-jeruk-nipis.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Jeruk Hangat',
                'slug' => 'jeruk-hangat',
                'description' => 'Sari buah jeruk asli hangat menenangkan tenggorokan dan menghangatkan tubuh.',
                'price' => 9091,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/jeruk-hangat.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Air Mineral Botol 600ml',
                'slug' => 'air-mineral-botol-600ml',
                'description' => 'Air mineral kemasan botol 600ml ukuran pas untuk pelepas dahaga.',
                'price' => 4545,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/air-mineral-botol-600ml.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Es Teh Manis',
                'slug' => 'es-teh-manis',
                'description' => 'Es teh manis wangi melati segar khas warung nusantara.',
                'price' => 5000,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/es-teh-manis.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Teh Hangat',
                'slug' => 'teh-hangat',
                'description' => 'Teh manis hangat beraroma wangi melati nikmat.',
                'price' => 5000,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/teh-hangat.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Teh Pucuk Harum',
                'slug' => 'teh-pucuk-harum',
                'description' => 'Teh kemasan Teh Pucuk Harum melati dingin yang menyegarkan.',
                'price' => 6000,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/teh-pucuk-harum.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Es Cendol Dawet',
                'slug' => 'es-cendol-dawet',
                'description' => 'Dawet cendol kenyal berpadu kuah santan gurih dan gula merah asli dengan es dingin menyegarkan.',
                'price' => 13636,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/es-cendol-dawet.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Es Sweet Greentea',
                'slug' => 'es-sweet-greentea',
                'description' => 'Teh hijau manis aroma harum greentea dingin yang sangat menyegarkan dahaga.',
                'price' => 10909,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/es-sweet-greentea.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Es Coklat',
                'slug' => 'es-coklat',
                'description' => 'Minuman coklat kental legit dan creamy disajikan dingin dengan es batu kristal segar.',
                'price' => 15000,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/es-coklat.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Coklat Hangat',
                'slug' => 'coklat-hangat',
                'description' => 'Sajian coklat kental hangat aroma manis lembut nikmat penenang suasana.',
                'price' => 15000,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/coklat-hangat.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Es Batu',
                'slug' => 'es-batu',
                'description' => 'Porsi ekstra es batu kristal higienis dan dingin segar untuk minuman Anda.',
                'price' => 2727,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/es-batu.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Es Strup Cincau',
                'slug' => 'es-strup-cincau',
                'description' => 'Sirup manis segar dipadukan dengan potongan cincau hitam kenyal dan es dingin pelepas dahaga.',
                'price' => 10909,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/es-strup-cincau.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],

            // 8. Menu Tambahan (Add-on)
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Selada Crispy',
                'slug' => 'selada-crispy',
                'description' => 'Daun selada segar digoreng tepung bumbu kriuk garing renyah penambah kenikmatan lauk.',
                'price' => 1818,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/selada-crispy.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Dadar Jagung',
                'slug' => 'dadar-jagung',
                'description' => 'Bakwan dadar jagung manis renyah khas Jawa Timur berbumbu daun jeruk harum.',
                'price' => 3182,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/dadar-jagung.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Kerupuk',
                'slug' => 'kerupuk',
                'description' => 'Kerupuk renyah pelengkap santap telur dadar dan sambal.',
                'price' => 4545,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => null,
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Sambal Ijo',
                'slug' => 'sambal-ijo-addon',
                'description' => 'Porsi ekstra sambal cabe ijo gurih pedas khas Dadar Beredar.',
                'price' => 4545,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/sambal-ijo-addon.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Nasi Putih',
                'slug' => 'nasi-putih',
                'description' => 'Satu porsi nasi putih pulen hangat.',
                'price' => 5455,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/nasi-putih.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Telur Dadar Crispy (Ala Carte)',
                'slug' => 'telur-dadar-crispy-alacarte',
                'description' => 'Satu butir telur dadar kress crispy renyah keriting ekstra tanpa nasi.',
                'price' => 5455,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-dadar-crispy-alacarte.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Nasi Daun Jeruk',
                'slug' => 'nasi-daun-jeruk',
                'description' => 'Nasi gurih bertabur irisan daun jeruk wangi penambah selera makan.',
                'price' => 6518,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/nasi-daun-jeruk.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Telur Ceplok (Ala Carte)',
                'slug' => 'telur-ceplok-alacarte',
                'description' => 'Satu butir telur ceplok goreng hangat tanpa nasi.',
                'price' => 6364,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-alacarte.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Telur Ceplok Bakar BBQ',
                'slug' => 'telur-ceplok-bakar-bbq',
                'description' => 'Telur ceplok dibakar dengan saus BBQ manis gurih beraroma asap menggugah selera.',
                'price' => 6364,
                'spiciness_level' => 1,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-bakar-bbq.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Sambal Ayam Suwir',
                'slug' => 'oseng-sambal-ayam-suwir',
                'description' => 'Porsi ekstra: Daging ayam suwir empuk dioseng dengan bumbu sambal pedas gurih.',
                'price' => 11818,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/oseng-sambal-ayam-suwir.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Sambal Ceker',
                'slug' => 'oseng-sambal-ceker',
                'description' => 'Porsi ekstra: Ceker ayam empuk dimasak oseng sambal pedas rempah gurih.',
                'price' => 12273,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/ceker-crispy.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Sambal Kulit',
                'slug' => 'oseng-sambal-kulit',
                'description' => 'Porsi ekstra: Kulit ayam krispy renyah dibalut bumbu oseng sambal pedas gurih mantap.',
                'price' => 12273,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/oseng-sambal-kulit.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Ayam Teriyaki',
                'slug' => 'oseng-ayam-teriyaki',
                'description' => 'Porsi ekstra: Potongan ayam empuk dengan siraman saus teriyaki manis gurih.',
                'price' => 12727,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/oseng-ayam-teriyaki.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Sambal Paru',
                'slug' => 'oseng-sambal-paru',
                'description' => 'Porsi ekstra: Paru sapi goreng bumbu gurih dioseng sambal cabai merah nikmat.',
                'price' => 13182,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/oseng-sambal-paru.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Cumi Teriyaki',
                'slug' => 'oseng-cumi-teriyaki',
                'description' => 'Porsi ekstra: Cumi kenyal gurih dibalut bumbu saus teriyaki manis harum.',
                'price' => 17273,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/oseng-cumi-teriyaki.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Sambal Cumi',
                'slug' => 'oseng-sambal-cumi',
                'description' => 'Porsi ekstra: Cumi segar dimasak oseng sambal pedas nendang bikin nambah nasi.',
                'price' => 17273,
                'spiciness_level' => 3,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/oseng-sambal-cumi.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],

            // 9. Upgrade & Biaya Tambahan
            [
                'category_id' => $catMap['upgrade-biaya-tambahan'],
                'name' => 'Upgrade Nasi Daun Jeruk',
                'slug' => 'upgrade-nasi-daun-jeruk',
                'description' => 'Tingkatkan kenikmatan paket menu Anda dengan upgrade ke Nasi Daun Jeruk wangi gurih.',
                'price' => 2273,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/nasi-daun-jeruk.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['upgrade-biaya-tambahan'],
                'name' => 'Upgrade Ceplok/Dadar Saos BBQ',
                'slug' => 'upgrade-ceplok-dadar-saos-bbq',
                'description' => 'Upgrade telur ceplok atau dadar pilihan Anda dengan balutan saos BBQ bakar gurih harum.',
                'price' => 2273,
                'spiciness_level' => 1,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => null,
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['upgrade-biaya-tambahan'],
                'name' => 'Tambahan Kotak Takeaway (Dadar/Ceplok Lugu)',
                'slug' => 'tambahan-kotak-takeaway-lugu',
                'description' => 'Tambahan kotak takeaway khusus pesanan menu Dadar Lugu atau Ceplok Lugu.',
                'price' => 2273,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => null,
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],

        ];

        foreach ($products as $prodData) {
            Product::updateOrCreate(['slug' => $prodData['slug']], $prodData);
        }

        // 5. Seed Authentic 5-Star Google Maps Reviews for Dadar Beredar Sidoarjo
        $reviews = [
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Rizky Pratama',
                'author_avatar' => null,
                'rating' => 5.0,
                'comment' => 'Dadar Beredar cabang Jl. Pahlawan Sidoarjo ini juara banget! Telur dadarnya kriwil super renyah tapi dalemnya tetap lembut gurih. Yang paling bikin nagih selada goreng krispinya sama sambal cuminya yang melimpah nampol abis! Tempatnya nyaman di lantai 2 ada AC, pelayanan stafnya juga gercep banget meski pas jam makan siang antre panjang. Resep Almarhum Babe Cabita beneran berkah.',
                'relative_time' => '2 minggu lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Dian Kusuma Wardhani',
                'author_avatar' => null,
                'rating' => 5.0,
                'comment' => 'Akhirnya Dadar Beredar buka di Sidoarjo Jl. Pahlawan! Nasi telur dadar sambal bakar + oseng paru wajib dipesan. Parunya beneran empuk, gurih, dan gak bau sama sekali. Porsi nasinya ngenyangin disajikan di atas daun pisang jadi makin sedap aromanya. Es Teh Jumbo 1 liternya seger parah buat penawar pedas. Rating 5/5 buat rasa dan kebersihannya!',
                'relative_time' => '1 bulan lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Ahmad Fauzi',
                'author_avatar' => null,
                'rating' => 5.0,
                'comment' => 'Salah satu kuliner telur paling nikmat di Sidoarjo. Telur dadar crispy-nya beneran kriuk sampai gigitan terakhir, selada krispinya gurih asin nagih. Sambal ijo dan sambal bakarnya pedas nikmat khas resep King Abdi dan Bang Babe. Lantai 2 adem ber-AC cocok buat makan bareng keluarga. Parkir mobil & motor ada jukir yang bantu dengan sigap.',
                'relative_time' => '3 minggu lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Nabila Putri Anggraini',
                'author_avatar' => null,
                'rating' => 5.0,
                'comment' => 'Makan siang di sini pesan Nasi Dadar Binal Ayam Suwir pedas level 2. Bumbunya meresap sampai ke serat daging, telur dadarnya mengembang garing sempurna. Suasananya bersih dan estetik komik seru. Harga ramah kantong mahasiswa cuma 20 ribuan udah kenyang bego. Bakal langganan terus kalau ke arah Alun-alun Sidoarjo!',
                'relative_time' => '1 bulan lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Bayu Aditya',
                'author_avatar' => null,
                'rating' => 5.0,
                'comment' => 'Sensasi telur dadar kriuk terenak di Sidoarjo seberang Wuling Jl. Pahlawan. Sambal paru dan kulit ayamnya kress maksimal. Keren banget konsepnya, pelayanannya ramah dan pesanan takeaway DAR-DOR cepat saji gak pake nunggu lama. Tribute luar biasa untuk mengenang Babe Cabita. Sukses terus Dadar Beredar Sidoarjo!',
                'relative_time' => '3 minggu lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Mega Sri Wahyuni',
                'author_avatar' => null,
                'rating' => 5.0,
                'comment' => 'Suka banget sama selada air krispinya, unik dan jarang nemu di tempat lain! Dipadukan sama nasi hangat dan telur ceplok bakar BBQ rasanya mantul tenan. Minumnya Es Badak Medan asli sarsaparilla segar nostalgia. Tempatnya luas 2 lantai, bersih, dan kasirnya ramah banget. Bintang 5 tanpa ragu!',
                'relative_time' => '2 minggu lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Hendro Wibowo',
                'author_avatar' => null,
                'rating' => 5.0,
                'comment' => 'Pelopor telur dadar krispy yang rasanya konsisten enak! Sambal cuminya banyak potongannya, gurih pedas nendang di lidah. Cabang Sidoarjo ini lokasinya gampang dijangkau di Jl. Pahlawan dekat GOR. Sangat recommended buat pecinta pedas!',
                'relative_time' => '4 hari lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Tri Wahyudi',
                'author_avatar' => null,
                'rating' => 5.0,
                'comment' => 'Udah berkali-kali repeat order delivery maupun makan langsung di cabang Sidokumpul Sidoarjo. Rasa telur dadar keritingnya gak pernah berubah, tetep crispy gurih. Oseng parunya empuk bumbu rempahnya meresap. Porsi pas, harga terjangkau!',
                'relative_time' => '1 minggu lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Anisa Rahmadani',
                'author_avatar' => null,
                'rating' => 5.0,
                'comment' => 'Tempat makan favorit keluarga di Sidoarjo! Anak-anak suka telur dadar gak pedas, sementara saya dan suami favorit sambal bakar level 3. Selada goreng tepungnya renyah kress. Pelayanan cepat dan ramah, top markotop!',
                'relative_time' => '2 minggu lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
        ];

        Review::query()->delete();
        foreach ($reviews as $revData) {
            Review::create($revData);
        }
    }
}
