<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Outlet;
use App\Models\Product;
use App\Models\Review;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Create Default Admin User
        User::updateOrCreate(
            ['email' => 'admin@dadarberedar.com'],
            [
                'name' => 'Admin Dadar Beredar',
                'password' => bcrypt('password123'),
            ]
        );

        // 2. Seed Outlets
        $outlets = [
            [
                'name' => 'Dadar Beredar Sidoarjo (Pusat Sidoarjo)',
                'slug' => 'dadar-beredar-sidoarjo',
                'city' => 'Sidoarjo',
                'province' => 'Jawa Timur',
                'address' => 'Jl. Pahlawan No. 45, Sidokumpul, Kec. Sidoarjo, Kabupaten Sidoarjo, Jawa Timur 61213 (Dekat Alun-alun & GOR Sidoarjo)',
                'latitude' => -7.447812,
                'longitude' => 112.718321,
                'phone' => '+62 812-3456-7890',
                'whatsapp' => '6281234567890',
                'opening_hours' => '10:00 - 22:30 WIB',
                'rating' => 4.9,
                'review_count' => 2840,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Sidoarjo',
                'gmaps_place_id' => 'ChIJsidoarjo_dadar_beredar_01',
                'gofood_url' => 'https://gofood.co.id/sidoarjo/restaurant/dadar-beredar-b91c890f-4886-42d8-9a63-71b69324e930',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurant/dadar-beredar-sidokumpul-delivery-menu/6-C3KTLNTKT2TGVA',
                'shopeefood_url' => 'https://shopee.co.id/search?keyword=Dadar%20Beredar%20Sidoarjo',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Waru Tropodo',
                'slug' => 'dadar-beredar-waru-tropodo',
                'city' => 'Sidoarjo',
                'province' => 'Jawa Timur',
                'address' => 'Jl. Raya Tropodo No. 88, Tropodo Wetan, Kec. Waru, Kabupaten Sidoarjo, Jawa Timur 61256 (Akses Strategis Juanda & Bundaran Waru)',
                'latitude' => -7.365420,
                'longitude' => 112.764850,
                'phone' => '+62 812-8899-7766',
                'whatsapp' => '6281288997766',
                'opening_hours' => '10:00 - 23:00 WIB',
                'rating' => 4.9,
                'review_count' => 1680,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Waru+Tropodo+Sidoarjo',
                'gmaps_place_id' => 'ChIJwaru_tropodo_dadar_05',
                'gofood_url' => 'https://gofood.co.id/sidoarjo/restaurant/dadar-beredar-waru-tropodo',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurants?search=Dadar%20Beredar%20Waru%20Tropodo',
                'shopeefood_url' => 'https://shopee.co.id/search?keyword=Dadar%20Beredar%20Tropodo%20Waru',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Surabaya MERR',
                'slug' => 'dadar-beredar-surabaya-merr',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'address' => 'Jl. Dr. Ir. H. Soekarno (MERR) No. 128, Rungkut, Surabaya, Jawa Timur 60298',
                'latitude' => -7.291240,
                'longitude' => 112.782410,
                'phone' => '+62 812-7890-1234',
                'whatsapp' => '6281278901234',
                'opening_hours' => '10:00 - 23:00 WIB',
                'rating' => 4.8,
                'review_count' => 3150,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Surabaya+MERR',
                'gmaps_place_id' => 'ChIJsurabaya_merr_dadar_02',
                'gofood_url' => 'https://gofood.co.id/surabaya/restaurant/dadar-beredar-surabaya-merr',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurants?search=Dadar%20Beredar%20MERR%20Surabaya',
                'shopeefood_url' => 'https://shopee.co.id/search?keyword=Dadar%20Beredar%20Surabaya',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Surabaya Barat (G-Walk)',
                'slug' => 'dadar-beredar-surabaya-barat',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'address' => 'Ruko Taman Gapura G-Walk CitraLand Blok K-15, Sambikerep, Surabaya Barat',
                'latitude' => -7.288500,
                'longitude' => 112.645200,
                'phone' => '+62 813-9876-5432',
                'whatsapp' => '6281398765432',
                'opening_hours' => '11:00 - 23:00 WIB',
                'rating' => 4.8,
                'review_count' => 1980,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Citraland+Surabaya',
                'gmaps_place_id' => 'ChIJgwalk_dadar_surabaya_03',
                'gofood_url' => 'https://gofood.co.id/surabaya/restaurant/dadar-beredar-gwalk',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurants?search=Dadar%20Beredar%20G-Walk%20Surabaya',
                'shopeefood_url' => 'https://shopee.co.id/search?keyword=Dadar%20Beredar%20Surabaya',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Tebet Jakarta Selatan',
                'slug' => 'dadar-beredar-tebet-jakarta',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'address' => 'Jl. Tebet Timur Dalam Raya No. 34, Tebet, Jakarta Selatan 12820',
                'latitude' => -6.228400,
                'longitude' => 106.853200,
                'phone' => '+62 811-2233-4455',
                'whatsapp' => '6281122334455',
                'opening_hours' => '10:00 - 23:00 WIB',
                'rating' => 4.9,
                'review_count' => 5420,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Tebet+Jakarta',
                'gmaps_place_id' => 'ChIJtebet_dadar_jakarta_04',
                'gofood_url' => 'https://gofood.co.id/jakarta/restaurant/dadar-beredar-tebet',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurants?search=Dadar%20Beredar%20Tebet%20Jakarta',
                'shopeefood_url' => 'https://shopee.co.id/search?keyword=Dadar%20Beredar%20Tebet',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Medan Marelan (Tanah Kelahiran Babe)',
                'slug' => 'dadar-beredar-medan-marelan',
                'city' => 'Medan',
                'province' => 'Sumatera Utara',
                'address' => 'Jl. Marelan Raya No. 88, Tanah Enam Ratus, Medan Marelan, Kota Medan 20245',
                'latitude' => 3.662100,
                'longitude' => 98.673400,
                'phone' => '+62 812-4455-6677',
                'whatsapp' => '6281244556677',
                'opening_hours' => '10:00 - 22:30 WIB',
                'rating' => 4.9,
                'review_count' => 4890,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Medan+Marelan',
                'gmaps_place_id' => 'ChIJmedan_dadar_babe_05',
                'gofood_url' => 'https://gofood.co.id/medan/restaurant/dadar-beredar-medan',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurants?search=Dadar%20Beredar%20Medan',
                'shopeefood_url' => 'https://shopee.co.id/search?keyword=Dadar%20Beredar%20Medan',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Bandung Dipatiukur',
                'slug' => 'dadar-beredar-bandung-dipatiukur',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'address' => 'Jl. Dipatiukur No. 72, Lebakgede, Coblong, Kota Bandung, Jawa Barat 40132',
                'latitude' => -6.892300,
                'longitude' => 107.618500,
                'phone' => '+62 821-3344-5566',
                'whatsapp' => '6282133445566',
                'opening_hours' => '10:00 - 22:00 WIB',
                'rating' => 4.8,
                'review_count' => 2640,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Dipatiukur+Bandung',
                'gmaps_place_id' => 'ChIJbandung_dadar_du_06',
                'gofood_url' => 'https://gofood.co.id/bandung/restaurant/dadar-beredar-dipatiukur',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurants?search=Dadar%20Beredar%20Bandung',
                'shopeefood_url' => 'https://shopee.co.id/search?keyword=Dadar%20Beredar%20Bandung',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Yogyakarta Seturan',
                'slug' => 'dadar-beredar-yogyakarta-seturan',
                'city' => 'Yogyakarta',
                'province' => 'DI Yogyakarta',
                'address' => 'Jl. Seturan Raya No. 16, Caturtunggal, Depok, Sleman, Yogyakarta 55281',
                'latitude' => -7.765400,
                'longitude' => 110.408200,
                'phone' => '+62 856-1122-3344',
                'whatsapp' => '6285611223344',
                'opening_hours' => '10:00 - 23:00 WIB',
                'rating' => 4.9,
                'review_count' => 3810,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Seturan+Jogja',
                'gmaps_place_id' => 'ChIJjogja_dadar_seturan_07',
                'gofood_url' => 'https://gofood.co.id/yogyakarta/restaurant/dadar-beredar-seturan',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurants?search=Dadar%20Beredar%20Jogja',
                'shopeefood_url' => 'https://shopee.co.id/search?keyword=Dadar%20Beredar%20Jogja',
                'is_active' => true,
            ],
            [
                'name' => 'Dadar Beredar Malang Soekarno Hatta',
                'slug' => 'dadar-beredar-malang-suhat',
                'city' => 'Malang',
                'province' => 'Jawa Timur',
                'address' => 'Jl. Soekarno Hatta No. 42B, Jatimulyo, Lowokwaru, Kota Malang 65141',
                'latitude' => -7.943200,
                'longitude' => 112.617400,
                'phone' => '+62 819-2233-4455',
                'whatsapp' => '6281922334455',
                'opening_hours' => '10:00 - 22:00 WIB',
                'rating' => 4.8,
                'review_count' => 2130,
                'gmaps_url' => 'https://maps.google.com/?q=Dadar+Beredar+Suhat+Malang',
                'gmaps_place_id' => 'ChIJmalang_suhat_dadar_08',
                'gofood_url' => 'https://gofood.co.id/malang/restaurant/dadar-beredar-suhat',
                'grabfood_url' => 'https://food.grab.com/id/id/restaurants?search=Dadar%20Beredar%20Malang',
                'shopeefood_url' => 'https://shopee.co.id/search?keyword=Dadar%20Beredar%20Malang',
                'is_active' => true,
            ]
        ];

        foreach ($outlets as $outletData) {
            Outlet::updateOrCreate(['slug' => $outletData['slug']], $outletData);
        }

        $sidoarjoOutlet = Outlet::where('slug', 'dadar-beredar-sidoarjo')->first();

        // 3. Seed Categories
        $categories = [
            [
                'name' => 'Telur Ceplok Original',
                'slug' => 'telur-ceplok-original',
                'type' => 'food',
                'icon' => '🍳',
                'sort_order' => 1,
            ],
            [
                'name' => 'Telur Dadar Original',
                'slug' => 'telur-dadar-original',
                'type' => 'food',
                'icon' => '🥞',
                'sort_order' => 2,
            ],
            [
                'name' => 'Telur Ceplok Bakar',
                'slug' => 'telur-ceplok-bakar',
                'type' => 'food',
                'icon' => '🔥',
                'sort_order' => 3,
            ],
            [
                'name' => 'Telur Dadar Bakar',
                'slug' => 'telur-dadar-bakar',
                'type' => 'food',
                'icon' => '🍳🔥',
                'sort_order' => 4,
            ],
            [
                'name' => 'Dargor & Menu Baru',
                'slug' => 'dargor-menu-baru',
                'type' => 'food',
                'icon' => '🥘',
                'sort_order' => 5,
            ],
            [
                'name' => 'Kids Meals',
                'slug' => 'kids-meals',
                'type' => 'food',
                'icon' => '👶',
                'sort_order' => 6,
            ],
            [
                'name' => 'Minuman Segar',
                'slug' => 'minuman-segar',
                'type' => 'beverage',
                'icon' => '🥤',
                'sort_order' => 7,
            ],
            [
                'name' => 'Menu Tambahan (Add-on)',
                'slug' => 'menu-tambahan',
                'type' => 'side',
                'icon' => '🥣',
                'sort_order' => 8,
            ],
            [
                'name' => 'Upgrade & Tambahan',
                'slug' => 'upgrade-biaya-tambahan',
                'type' => 'side',
                'icon' => '➕',
                'sort_order' => 9,
            ],
        ];

        $catMap = [];
        foreach ($categories as $catData) {
            $category = Category::updateOrCreate(['slug' => $catData['slug']], $catData);
            $catMap[$catData['slug']] = $category->id;
        }

        // 4. Seed Products
        $products = [
            // 1. Telur Ceplok Original
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Lugu',
                'slug' => 'telur-ceplok-lugu',
                'description' => 'Telur ceplok goreng lezat khas Dadar Beredar dengan racikan bumbu lugu gurih nikmat.',
                'price' => 12273,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-ceplok-lugu.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Ayam Suwir',
                'slug' => 'telur-ceplok-ayam-suwir',
                'description' => 'Telur ceplok hangat disajikan dengan topping ayam suwir gurih berbumbu rempah meresap.',
                'price' => 24091,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/ayam-suwir.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Ceker',
                'slug' => 'telur-ceplok-ceker',
                'description' => 'Telur ceplok nikmat dipadukan dengan olahan ceker empuk bumbu gurih lezat.',
                'price' => 25000,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/ceker-crispy.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Kulit',
                'slug' => 'telur-ceplok-kulit',
                'description' => 'Telur ceplok disajikan bersama kulit ayam goreng renyah kriuk berselimut bumbu khas.',
                'price' => 25000,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/kulit-crispy.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Paru',
                'slug' => 'telur-ceplok-paru',
                'description' => 'Telur ceplok mantap disandingkan dengan paru sapi goreng gurih tanpa alot.',
                'price' => 26818,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/paru-goreng.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Ayam Teriyaki',
                'slug' => 'telur-ceplok-ayam-teriyaki',
                'description' => 'Telur ceplok dipadukan dengan ayam saus teriyaki manis gurih lezat menggoda selera.',
                'price' => 26363,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/ayam-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Cumi Teriyaki',
                'slug' => 'telur-ceplok-cumi-teriyaki',
                'description' => 'Telur ceplok lezat dengan potongan cumi kenyal berbalut saus teriyaki manis gurih.',
                'price' => 28636,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/cumi-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-original'],
                'name' => 'Telur Ceplok Cumi',
                'slug' => 'telur-ceplok-cumi',
                'description' => 'Telur ceplok spesial dengan olahan cumi gurih pedas nikmat menggugah selera.',
                'price' => 28636,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/cumi-sambal.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],

            // 2. Telur Dadar Original
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Lugu',
                'slug' => 'telur-dadar-lugu',
                'description' => 'Telur dadar kress keriting renyah khas Dadar Beredar dengan bumbu lugu gurih.',
                'price' => 12273,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-dadar-lugu.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Ayam Suwir',
                'slug' => 'telur-dadar-ayam-suwir',
                'description' => 'Telur dadar kress dengan taburan ayam suwir bumbu gurih lezat melimpah.',
                'price' => 23636,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/ayam-suwir.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Ceker',
                'slug' => 'telur-dadar-ceker',
                'description' => 'Telur dadar renyah disajikan dengan olahan ceker empuk bumbu rempah nikmat.',
                'price' => 24545,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/ceker-crispy.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Kulit',
                'slug' => 'telur-dadar-kulit',
                'description' => 'Telur dadar crispy gurih disandingkan dengan kulit ayam kriuk renyah maksimal.',
                'price' => 24545,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/kulit-crispy.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Paru',
                'slug' => 'telur-dadar-paru',
                'description' => 'Telur dadar crispy berpadu dengan paru goreng gurih empuk khas Dadar Beredar.',
                'price' => 26364,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/paru-goreng.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Ayam Teriyaki',
                'slug' => 'telur-dadar-ayam-teriyaki',
                'description' => 'Telur dadar gurih disiram topping ayam teriyaki manis legit beraroma khas.',
                'price' => 25455,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/ayam-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Cumi Teriyaki',
                'slug' => 'telur-dadar-cumi-teriyaki',
                'description' => 'Telur dadar renyah dipadukan dengan cumi teriyaki manis gurih istimewa.',
                'price' => 28182,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/cumi-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-original'],
                'name' => 'Telur Dadar Cumi',
                'slug' => 'telur-dadar-cumi',
                'description' => 'Telur dadar crispy legendaris ditemani olahan cumi pedas gurih sedap.',
                'price' => 28182,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/cumi-sambal.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],

            // 3. Telur Ceplok Bakar
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Ayam Suwir',
                'slug' => 'telur-ceplok-bakar-ayam-suwir',
                'description' => 'Telur ceplok bakar bumbu smokey dipadukan dengan ayam suwir gurih lezat.',
                'price' => 25000,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-bakar.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Ceker',
                'slug' => 'telur-ceplok-bakar-ceker',
                'description' => 'Telur ceplok bakar aroma arang sedap ditemani ceker empuk bumbu bakar pedas manis.',
                'price' => 25909,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/ceker-crispy.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Kulit',
                'slug' => 'telur-ceplok-bakar-kulit',
                'description' => 'Telur ceplok bakar bumbu rempah bakar disajikan bersama kulit ayam krispy gurih.',
                'price' => 25909,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/kulit-crispy.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Paru',
                'slug' => 'telur-ceplok-bakar-paru',
                'description' => 'Telur ceplok bakar harum smokey dipadu paru goreng gurih empuk memanjakan lidah.',
                'price' => 27727,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/paru-goreng.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Ayam Teriyaki',
                'slug' => 'telur-ceplok-bakar-ayam-teriyaki',
                'description' => 'Telur ceplok bakar dengan paduan ayam saus teriyaki manis gurih beraroma bakar.',
                'price' => 26818,
                'spiciness_level' => 1,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/ayam-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Cumi Teriyaki',
                'slug' => 'telur-ceplok-bakar-cumi-teriyaki',
                'description' => 'Telur ceplok bakar istimewa berpadu dengan cumi bumbu teriyaki manis legit.',
                'price' => 29545,
                'spiciness_level' => 1,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/cumi-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-ceplok-bakar'],
                'name' => 'Telur Ceplok Bakar Cumi',
                'slug' => 'telur-ceplok-bakar-cumi',
                'description' => 'Telur ceplok bakar harum smokey dengan olahan cumi pedas gurih bumbu rempah bakar.',
                'price' => 29545,
                'spiciness_level' => 3,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/cumi-sambal.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],

            // 4. Telur Dadar Bakar
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Ayam Suwir',
                'slug' => 'telur-dadar-bakar-ayam-suwir',
                'description' => 'Telur dadar tebal dibakar bumbu rempah manis gurih disandingkan dengan ayam suwir lezat.',
                'price' => 24545,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-dadar-bakar.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Ceker',
                'slug' => 'telur-dadar-bakar-ceker',
                'description' => 'Telur dadar bakar aroma rempah arang sedap dengan ceker pedas empuk meresap.',
                'price' => 25455,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/ceker-crispy.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Kulit',
                'slug' => 'telur-dadar-bakar-kulit',
                'description' => 'Telur dadar bakar gurih smokey ditemani kulit ayam goreng super renyah.',
                'price' => 25455,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/kulit-crispy.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Paru',
                'slug' => 'telur-dadar-bakar-paru',
                'description' => 'Menu andalan! Telur dadar tebal dibakar smokey berpadu paru sapi empuk gurih juara.',
                'price' => 27273,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/paru-goreng.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Ayam Teriyaki',
                'slug' => 'telur-dadar-bakar-ayam-teriyaki',
                'description' => 'Telur dadar bakar gurih disajikan dengan topping ayam bumbu teriyaki manis mantap.',
                'price' => 26818,
                'spiciness_level' => 1,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/ayam-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Cumi Teriyaki',
                'slug' => 'telur-dadar-bakar-cumi-teriyaki',
                'description' => 'Telur dadar bakar harum bumbu spesial dipadu cumi empuk berbalut saus teriyaki gurih.',
                'price' => 29091,
                'spiciness_level' => 1,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/cumi-teriyaki.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['telur-dadar-bakar'],
                'name' => 'Telur Dadar Bakar Cumi',
                'slug' => 'telur-dadar-bakar-cumi',
                'description' => 'Kombinasi terfavorit! Telur dadar bakar aroma smokey dengan olahan cumi pedas nikmat nendang.',
                'price' => 29091,
                'spiciness_level' => 3,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/cumi-sambal.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],

            // 5. Dargor & Menu Baru
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Ceker Crispy',
                'slug' => 'ceker-crispy',
                'description' => 'Ceker ayam pilihan digoreng super renyah kriuk dengan balutan tepung bumbu rempah gurih khas Dadar Beredar.',
                'price' => 9545,
                'spiciness_level' => 1,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/ceker-crispy.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Dargor Ayam Suwir',
                'slug' => 'dargor-ayam-suwir',
                'description' => 'Sajian Dargor spesial berpadu suwiran daging ayam gurih bumbu rempah meresap mantap.',
                'price' => 25000,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/ayam-suwir.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Dargor Kulit',
                'slug' => 'dargor-kulit',
                'description' => 'Dargor renyah disajikan dengan topping kulit ayam goreng krispy keemasan yang gurih maksimal.',
                'price' => 25909,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/kulit-crispy.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Dargor Ceker',
                'slug' => 'dargor-ceker',
                'description' => 'Dargor khas dipadukan dengan olahan ceker empuk berbumbu pedas manis sedap.',
                'price' => 25909,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/ceker-crispy.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Dargor Paru',
                'slug' => 'dargor-paru',
                'description' => 'Kombinasi juara Dargor dengan paru sapi goreng gurih renyah tanpa bau amis.',
                'price' => 27727,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/paru-goreng.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Dargor Cumi',
                'slug' => 'dargor-cumi',
                'description' => 'Sajian Dargor istimewa bertabur potongan cumi empuk gurih bumbu pedas nampol.',
                'price' => 29545,
                'spiciness_level' => 3,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/cumi-sambal.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['dargor-menu-baru'],
                'name' => 'Dargor Daging',
                'slug' => 'dargor-daging',
                'description' => 'Menu premium Dargor dengan potongan daging sapi empuk berbumbu rempah spesial kaya rasa.',
                'price' => 39545,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/dargor-daging.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],

            // 6. Kids Meals
            [
                'category_id' => $catMap['kids-meals'],
                'name' => 'Kids Meal: Ceplok Ayam Teriyaki',
                'slug' => 'kids-meal-ceplok-ayam-teriyaki',
                'description' => 'Porsi pas untuk si kecil: Nasi hangat, telur ceplok empuk, dan potongan ayam saus teriyaki manis gurih tanpa pedas.',
                'price' => 24545,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/kids-meal.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['kids-meals'],
                'name' => 'Kids Meal: Dadar Ayam Teriyaki',
                'slug' => 'kids-meal-dadar-ayam-teriyaki',
                'description' => 'Porsi favorit anak: Nasi hangat, telur dadar kress gurih lembut, dan ayam bumbu teriyaki manis lezat.',
                'price' => 23182,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/kids-meal.jpg',
                'type' => 'food',
                'stock' => 999,
                'is_available' => true,
            ],

            // 7. Minuman Segar
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Es Kopi Susu Botol',
                'slug' => 'es-kopi-susu-botol',
                'description' => 'Kopi susu gula aren creamy dalam botol praktis siap minum, perpaduan manis gurih pas teman makan telur dadar.',
                'price' => 10909,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/es-kopi-susu.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Es Blackcurrant Squash',
                'slug' => 'es-blackcurrant-squash',
                'description' => 'Sensasi soda dingin dipadu sirup blackcurrant manis asam segar ampuh melepas dahaga.',
                'price' => 12727,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/es-blackcurrant-squash.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Es Jeruk Nipis',
                'slug' => 'es-jeruk-nipis',
                'description' => 'Jeruk nipis peras asli disajikan dingin dengan es batu kristal yang asam manis segar alami.',
                'price' => 9091,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/es-jeruk.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Jeruk Hangat',
                'slug' => 'jeruk-hangat',
                'description' => 'Sari buah jeruk asli hangat menenangkan tenggorokan dan menghangatkan tubuh.',
                'price' => 9091,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/jeruk-hangat.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Air Mineral Botol 600ml',
                'slug' => 'air-mineral-botol-600ml',
                'description' => 'Air mineral kemasan botol 600ml ukuran pas untuk pelepas dahaga.',
                'price' => 4545,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/air-mineral.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Es Teh Manis',
                'slug' => 'es-teh-manis',
                'description' => 'Es teh manis wangi melati segar khas warung nusantara.',
                'price' => 5000,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/es-teh.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Teh Hangat',
                'slug' => 'teh-hangat',
                'description' => 'Teh manis hangat beraroma wangi melati nikmat.',
                'price' => 5000,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/teh-hangat.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['minuman-segar'],
                'name' => 'Teh Pucuk Harum',
                'slug' => 'teh-pucuk-harum',
                'description' => 'Teh kemasan Teh Pucuk Harum melati dingin yang menyegarkan.',
                'price' => 6000,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/es-teh.jpg',
                'type' => 'beverage',
                'stock' => 999,
                'is_available' => true,
            ],

            // 8. Menu Tambahan (Add-on)
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Selada Crispy',
                'slug' => 'selada-crispy',
                'description' => 'Daun selada segar digoreng tepung bumbu kriuk garing renyah penambah kenikmatan lauk.',
                'price' => 1818,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/selada-crispy.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Dadar Jagung',
                'slug' => 'dadar-jagung',
                'description' => 'Bakwan dadar jagung manis renyah khas Jawa Timur berbumbu daun jeruk harum.',
                'price' => 3182,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/dadar-jagung.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Kerupuk',
                'slug' => 'kerupuk',
                'description' => 'Kerupuk renyah pelengkap santap telur dadar dan sambal.',
                'price' => 4545,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/kerupuk.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Sambal Ijo',
                'slug' => 'sambal-ijo-addon',
                'description' => 'Porsi ekstra sambal cabe ijo gurih pedas khas Dadar Beredar.',
                'price' => 4545,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/sambal-ijo.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Nasi Putih',
                'slug' => 'nasi-putih',
                'description' => 'Satu porsi nasi putih pulen hangat.',
                'price' => 5455,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/nasi-putih.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Telur Dadar Crispy (Ala Carte)',
                'slug' => 'telur-dadar-crispy-alacarte',
                'description' => 'Satu butir telur dadar kress crispy renyah keriting ekstra tanpa nasi.',
                'price' => 5455,
                'spiciness_level' => 0,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/telur-dadar-lugu.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Nasi Daun Jeruk',
                'slug' => 'nasi-daun-jeruk',
                'description' => 'Nasi gurih bertabur irisan daun jeruk wangi penambah selera makan.',
                'price' => 6518,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/nasi-daun-jeruk.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Telur Ceplok (Ala Carte)',
                'slug' => 'telur-ceplok-alacarte',
                'description' => 'Satu butir telur ceplok goreng hangat tanpa nasi.',
                'price' => 6364,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-lugu.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Telur Ceplok Bakar BBQ',
                'slug' => 'telur-ceplok-bakar-bbq',
                'description' => 'Telur ceplok dibakar dengan saus BBQ manis gurih beraroma asap menggugah selera.',
                'price' => 6364,
                'spiciness_level' => 1,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/telur-ceplok-bakar.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Sambal Ayam Suwir',
                'slug' => 'oseng-sambal-ayam-suwir',
                'description' => 'Porsi ekstra: Daging ayam suwir empuk dioseng dengan bumbu sambal pedas gurih.',
                'price' => 11818,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/ayam-suwir.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Sambal Ceker',
                'slug' => 'oseng-sambal-ceker',
                'description' => 'Porsi ekstra: Ceker ayam empuk dimasak oseng sambal pedas rempah gurih.',
                'price' => 12273,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/ceker-crispy.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Sambal Kulit',
                'slug' => 'oseng-sambal-kulit',
                'description' => 'Porsi ekstra: Kulit ayam krispy renyah dibalut bumbu oseng sambal pedas gurih mantap.',
                'price' => 12273,
                'spiciness_level' => 2,
                'is_crispy' => true,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/kulit-crispy.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Ayam Teriyaki',
                'slug' => 'oseng-ayam-teriyaki',
                'description' => 'Porsi ekstra: Potongan ayam empuk dengan siraman saus teriyaki manis gurih.',
                'price' => 12727,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/ayam-teriyaki.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Sambal Paru',
                'slug' => 'oseng-sambal-paru',
                'description' => 'Porsi ekstra: Paru sapi goreng bumbu gurih dioseng sambal cabai merah nikmat.',
                'price' => 13182,
                'spiciness_level' => 2,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/paru-goreng.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Cumi Teriyaki',
                'slug' => 'oseng-cumi-teriyaki',
                'description' => 'Porsi ekstra: Cumi kenyal gurih dibalut bumbu saus teriyaki manis harum.',
                'price' => 17273,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/cumi-teriyaki.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['menu-tambahan'],
                'name' => 'Oseng Sambal Cumi',
                'slug' => 'oseng-sambal-cumi',
                'description' => 'Porsi ekstra: Cumi segar dimasak oseng sambal pedas nendang bikin nambah nasi.',
                'price' => 17273,
                'spiciness_level' => 3,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => true,
                'image_url' => '/images/menu/cumi-sambal.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],

            // 9. Upgrade & Biaya Tambahan
            [
                'category_id' => $catMap['upgrade-biaya-tambahan'],
                'name' => 'Upgrade Nasi Daun Jeruk',
                'slug' => 'upgrade-nasi-daun-jeruk',
                'description' => 'Tingkatkan kenikmatan paket menu Anda dengan upgrade ke Nasi Daun Jeruk wangi gurih.',
                'price' => 2273,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/nasi-daun-jeruk.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['upgrade-biaya-tambahan'],
                'name' => 'Upgrade Ceplok/Dadar Saos BBQ',
                'slug' => 'upgrade-ceplok-dadar-saos-bbq',
                'description' => 'Upgrade telur ceplok atau dadar pilihan Anda dengan balutan saos BBQ bakar gurih harum.',
                'price' => 2273,
                'spiciness_level' => 1,
                'is_crispy' => false,
                'is_bestseller' => true,
                'is_signature' => false,
                'image_url' => '/images/menu/saos-bbq.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],
            [
                'category_id' => $catMap['upgrade-biaya-tambahan'],
                'name' => 'Tambahan Kotak Takeaway (Dadar/Ceplok Lugu)',
                'slug' => 'tambahan-kotak-takeaway-lugu',
                'description' => 'Tambahan kotak takeaway khusus pesanan menu Dadar Lugu atau Ceplok Lugu.',
                'price' => 2273,
                'spiciness_level' => 0,
                'is_crispy' => false,
                'is_bestseller' => false,
                'is_signature' => false,
                'image_url' => '/images/menu/kotak-takeaway.jpg',
                'type' => 'side',
                'stock' => 999,
                'is_available' => true,
            ],

        ];

        foreach ($products as $prodData) {
            Product::updateOrCreate(['slug' => $prodData['slug']], $prodData);
        }

        // 5. Seed Real-feeling Google Reviews
        $reviews = [
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Dimas Prasetyo',
                'author_avatar' => 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
                'rating' => 5.0,
                'comment' => 'Cabang Sidoarjo Jl. Pahlawan ini langganan keluarga tiap weekend! Telur dadarnya super kress crispy di luar tapi tetep lembut di dalem. Sambal bakarnya pedas nikmat bikin nagih. Tribute buat almarhum Babe Cabita, karya kulinernya bener-bener berkah!',
                'relative_time' => '2 hari yang lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Siti Aisyah Rahmawati',
                'author_avatar' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
                'rating' => 5.0,
                'comment' => 'Harga mahasiswa, porsi kenyang, rasa hotel bintang lima! Paru gorengnya renyah banget ga ada alotnya sama sekali. Ditambah es teh jumbo 1 liter seger parah. Sukses selalu Dadar Beredar!',
                'relative_time' => '5 hari yang lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Budi Santoso',
                'author_avatar' => 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
                'rating' => 5.0,
                'comment' => 'Pesanan DAR-DOR takeaway lewat web cepet banget diproses. Pas nyampe rumah telurnya masih kress renyah hangat. Pelayanan ramah khas Sidoarjo. Wajib coba Sambal Bakar level 3!',
                'relative_time' => '1 minggu yang lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Clara Novita',
                'author_avatar' => 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
                'rating' => 5.0,
                'comment' => 'Beli paket komplit sambal bakar cumi sama telur dadar kress, rasanya juara banget! Sambal cuminya isi melimpah ga pelit. Rest in peace Bang Babe, karyamu membawa berkah!',
                'relative_time' => '2 minggu yang lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
            [
                'outlet_id' => $sidoarjoOutlet ? $sidoarjoOutlet->id : null,
                'author_name' => 'Rian Hidayat',
                'author_avatar' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
                'rating' => 4.9,
                'comment' => 'Es Badak Medan-nya beneran otentik! Jarang nemu sarsaparilla Cap Badak di Jawa Timur. Paduan telur dadar pedas ketemu soda sarsaparilla dingin bener-bener combo surga duniawi.',
                'relative_time' => '3 minggu yang lalu',
                'verified_buyer' => true,
                'is_featured' => true,
            ],
        ];

        foreach ($reviews as $revData) {
            Review::create($revData);
        }
    }
}
